/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface SampleLetter {
  id: string;
  source: string;
  title: string;
  docType: "letter" | "file" | "report";
  text: string;
}

export const sampleLetters: SampleLetter[] = [
  {
    id: "sample-1",
    source: "Ministry of Lands & Physical Planning",
    title: "Request for Urgent Resolution of Kabale Boundary Boundary Claims",
    docType: "letter",
    text: `To: Commissioner of Land Administration
From: Permanent Secretary, Lands, Housing and Urban Development
Date: June 15, 2026
Subject: Immediate boundaries boundary assessment and land survey in Kabale Municipality.

We have received multiple complaints regarding overlapping land boundaries on freehold registration holdings block 402, plot 15. The public survey office must initiate a site verification immediately.

This dispute is disrupting public utility installations and is marked as urgent due to high public tension and active court summons. Please compile the deed plans and dispatch the senior registrar surveyor to the coordinates ASAP. This matter is confidential until resolved to prevent speculative trading.`
  },
  {
    id: "sample-2",
    source: "NSSF Restructuring Taskforce",
    title: "Draft Human Capital Restructuring Strategy - Phase III",
    docType: "report",
    text: `TITLE: NATIONAL ARCHIVAL RESTRUCTURING AND CIVIL REDISTRIBUTION PLAN (FY26)
SECRETARY MINUTE CABINET MEMO

This document outlines the systematic re-deployment of clerical assistants across 15 provincial registry centers. To implement sustainable tech-based workflows:
1. Archival rooms are limited to authorized personnel with Secret-tier security clearance.
2. Index sorting clerks in grade G-12 are relocated to server audit validation teams.
3. Retroactive scan logs must be completed.

Total budget reallocation is estimated at 340,000,000 Shilling, with a target completion date of September 30, 2026. Reviewing officers must confirm compliance with Public Service Act Cap 277.`
  },
  {
    id: "sample-3",
    source: "Ministry of ICT and National Guidance",
    title: "Notification of Secure Cloud Infrastructure Deployment",
    docType: "file",
    text: `To: All Accounting Officers and Directors of Communication
RE: DEPLOYMENT OF THE CENTRALIZIED GOVERNMENT DATA MANAGEMENT INTERFACE (GDMI)

Following Cabinet Directive No. 49, all ministries are directed to commence transition away from manual physical cabinet indices. The loss rate of physical papers has reached unsustainable thresholds. 

The National Archives will establish a decentralized hosting model. Encryption keys must be strictly generated by the Security Agency. Open public files will be available via standard web proxies, whereas RESTRICTED internal policy cabinets can only be requisitioned on a 3-day hold. Implementing teams must log movement checks using electronic digital signatures.`
  }
];
